# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

mi_tupla = (1,2,3, "hola", True)
print(mi_tupla)

t = (1,1,2,3,3,3)
print(t)

lista = [1,2,3]
print(lista)

tupla = (1,2,3)
print(tupla)

lista[0]=10
print(lista)

tupla[0]=10
print(tupla)

coordenadas = (40.7128, -74.0060)
coordenadas[0] = 41.0

tupla1 = (1,2,3)
tupla2 = ("a","b","c")
tupla3 = (1, "hola", 3.5)
tupla4 = ()
tupla5 = (5,)
print(tupla1)
print(tupla2)
print(tupla3)
print(tupla4)
print(tupla5)

tupla = ("Python", 2025, True)
print(tupla[0])
print(tupla[1])
print(tupla[-1])

tupla = (10, 20, 30, 40, 50)
print(tupla[1:4])
print(tupla[:3])
print(tupla[::2])

colores = ("rojo", "verde", "azul")
for color in colores:
  print(color)

t = ((1,2), (3,4), (5,6))
print(t[0])
print(t[0][1])

t1 = (1, 2, 3)
t2 = (4, 5, 6)
resultado = t1 + t2
print(resultado)

t = ("Python",)*3
print(t)

t = (10,20,30,40)
print(20 in t)
print(50 not in t)

persona = ("Nicolas", 22, "Colombia")
nombre, edad, pais = persona
print(nombre)
print(edad)
print(pais)

t = (1,2,2,3,4,)
print(t.count(2))
print(t.index(3))

t = (5,1,7,3)
print(len(t))
print(max(t))
print(min(t))
print(sum(t))
print(sorted(t))

lista = [1,2,3]
tupla = tuple(lista)
print(tupla)

nueva_lista = list(tupla)
print(nueva_lista)

persona = ("Nicolas", 22, "Colombia")
print("Nombre:", persona[0])
print("Edad:", persona[1])
print("País:", persona[2])

coordenadas = {}
punto = (10, 20)
coordenadas[punto] = "Ubicación A"
print(coordenadas)

def operaciones(a, b):
  return a + b, a - b, a * b

suma, resta, producto = operaciones(5, 3)
print(suma, resta, producto)

frutas = ("manzana", "pera", "uva")
for i, fruta in enumerate(frutas):
  print(i, fruta)

a,b = 10,20
a,b = b, a
print(a,b)

# Ejercicio 1 – Crear una tupla
t = (1, 2, 3, 4, 5)
print(t) # (1, 2, 3, 4, 5)

# Ejercicio 2 – Acceder al tercer elemento
t = (10, 20, 30, 40, 50)
print(t[2]) # 30

# Ejercicio 3 – Tupla con nombre y edad
info = ("Nicolás", 22)
print("Nombre:", info[0], "Edad:", info[1])

# Ejercicio 4 – Concatenar tuplas
t1 = (1, 2, 3)
t2 = (4, 5, 6)
print(t1 + t2) # (1, 2, 3, 4, 5, 6)

# Ejercicio 5 – Repetir una tupla
t = ("Python",) * 3
print(t) # ('Python', 'Python', 'Python')
# Ejercicio 6 – Verificar pertenencia
t = (5, 10, 15, 20, 25)
print(20 in t) # True

# Ejercicio 7 – Desempaquetar tupla
paises = ("Colombia", "México", "Argentina")
a, b, c = paises
print(a, b, c) # Colombia México Argentina

# Ejercicio 8 – Tupla anidada
t = ((1, 2), (3, 4))
print(t[1][1]) # 4

# Ejercicio 9 – Función con suma y producto
def operaciones(a, b):
    return a+b, a*b
print(operaciones(3, 5)) # (8, 15)

# Ejercicio 10 – Intercambio de valores
a, b = 7, 9
a, b = b, a
print(a, b) # 9 7

# Ejercicio 11 – Contar apariciones
t = (2, 4, 6, 2, 8, 2)
print(t.count(2)) # 3

# Ejercicio 12 – Índice de un valor
t = (10, 20, 30, 40, 50)
print(t.index(50)) # 4

# Ejercicio 13 – Funciones integradas
t = (4, 7, 1, 9, 3)
print(max(t)) # 9
print(min(t)) # 1
print(sum(t)) # 24

# Ejercicio 14 – Convertir lista a tupla
lista = [10, 20, 30]
t = tuple(lista)
print(t) # (10, 20, 30)

# Ejercicio 15 – Enumerate con tuplas
colores = ("rojo", "verde", "azul")
for i, color in enumerate(colores):
    print(i, color)

